---
- name: Check if the Jenkins user has already been created
  stat:
    path: "{{ jenkins_home }}/users/{{ username }}/config.xml"
  register: chkuser

- name: Make sure the user directory exists
  file:
    path: "{{ jenkins_home }}/users/{{ username }}"
    state: directory
    owner: jenkins
    group: jenkins
    mode: 0755

- name: Create jenkins user configure file if it does not exist
  template:
    src: "config-user.xml.j2"
    dest: "{{ jenkins_home }}/users/{{ username }}/config.xml"
    owner: jenkins
    group: jenkins
    force: false
    mode: 0644



 - name: Create Jenkins using jenkins-cli
   shell: echo '{{ lookup("template", "./groovy-create-user.j2") }}' | java -jar {{ jenkins_home }}/jenkins-cli.jar -s http://{{ jenkins_hostname }}:{{ jenkins_http_port }} groovy =
   when: chkuser.stat.exists == False
